<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Audit Coverage Report - {{ $docNumber }}</title>
    <style>
        @page {
            margin: 155px 30px 65px 30px;
        }
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 8px;
            color: #333;
            line-height: 1.3;
        }
        header {
            position: fixed;
            top: -135px;
            left: 0;
            right: 0;
            height: 125px;
            border-bottom: 1px solid #000;
        }
        footer {
            position: fixed;
            bottom: -45px;
            left: 0;
            right: 0;
            height: 25px;
        }
        .company-name {
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
            text-align: center;
            margin: 0;
            color: #000;
        }
        .wms-subname {
            font-size: 9px;
            text-align: center;
            margin: 2px 0 0 0;
            color: #475569;
            text-transform: uppercase;
            font-weight: 500;
        }
        .header-title {
            font-size: 11px;
            font-weight: bold;
            text-transform: uppercase;
            text-align: center;
            margin: 4px 0 0 0;
            color: #000;
            letter-spacing: 0.5px;
        }
        .doc-number {
            font-size: 9px;
            font-weight: bold;
            text-align: center;
            margin: 2px 0 0 0;
            color: #000;
        }
        .header-meta {
            width: 100%;
            margin-top: 6px;
        }
        .header-meta td {
            font-size: 8px;
            padding: 1px 0;
            vertical-align: top;
        }
        .content-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }
        .content-table th {
            background-color: #f8fafc;
            color: #334155;
            font-weight: bold;
            font-size: 8px;
            text-transform: uppercase;
            border: 1px solid #cbd5e1;
            padding: 4px 5px;
            text-align: left;
        }
        .content-table td {
            border: 1px solid #cbd5e1;
            padding: 4px 5px;
            font-size: 8px;
            vertical-align: middle;
        }
        thead {
            display: table-header-group;
        }
        .content-table tr {
            page-break-inside: avoid;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .status-badge {
            font-weight: bold;
            text-transform: uppercase;
            font-size: 7.5px;
        }
        .status-green {
            color: #16a34a;
        }
        .status-yellow {
            color: #d97706;
        }
        .status-red {
            color: #dc2626;
        }
        .overdue-text {
            color: #dc2626;
            font-weight: bold;
        }
        .page-number:before {
            content: counter(page);
        }
        .total-pages:before {
            content: counter(pages);
        }
    </style>
</head>
<body>
    <header>
        <div style="border-top: 1px solid #000; border-bottom: 1px solid #000; padding: 4px 0;">
            <div class="company-name">PT PERONI KARYA SENTRA</div>
            <div class="wms-subname">Warehouse Management System</div>
            <div class="header-title">AUDIT COVERAGE REPORT</div>
            <div class="doc-number">Ref. No: {{ $docNumber }}</div>
        </div>
        
        <table class="header-meta" style="width: 100%; border-collapse: collapse;">
            <tr>
                <td style="width: 15%; font-weight: bold;">Warehouse</td>
                <td style="width: 35%;">: {{ $warehouseName }}</td>
                <td style="width: 15%; font-weight: bold;">Generated Date</td>
                <td style="width: 35%;">: {{ $generatedDate }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Bin Location</td>
                <td>: {{ $binCode }}</td>
                <td style="font-weight: bold;">Generated Time</td>
                <td>: {{ $generatedTime }} WIB</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Filter State</td>
                <td style="text-transform: capitalize;">: {{ $filterState }}</td>
                <td style="font-weight: bold;">Generated By</td>
                <td>: {{ $generatedBy }}</td>
            </tr>
        </table>
    </header>

    <footer>
        <table style="width: 100%; border-top: 1px solid #cbd5e1; padding-top: 4px; font-size: 7px; color: #64748b;">
            <tr>
                <td>Generated from Warehouse Management System | Timestamp: {{ $generationTimestamp }}</td>
                <td style="text-align: right;">
                    Page <span class="page-number"></span> of <span class="total-pages"></span>
                </td>
            </tr>
        </table>
    </footer>

    <!-- SUMMARY SECTION -->
    <div class="summary-box" style="border: 1px solid #cbd5e1; background-color: #f8fafc; padding: 6px 10px; page-break-inside: avoid;">
        <div style="font-weight: bold; font-size: 8px; text-transform: uppercase; border-bottom: 1px solid #cbd5e1; padding-bottom: 3px; margin-bottom: 5px; color: #1e293b; letter-spacing: 0.3px;">
            Audit Coverage Summary Table
        </div>
        <table style="width: 100%; border-collapse: collapse; font-size: 8px;">
            <tr>
                <td style="width: 16%; font-weight: bold; color: #475569; padding: 2px 0;">Total Items</td>
                <td style="width: 16%; font-weight: bold; color: #475569; padding: 2px 0;">Audited (Recent)</td>
                <td style="width: 16%; font-weight: bold; color: #475569; padding: 2px 0;">Audit Aging</td>
                <td style="width: 16%; font-weight: bold; color: #475569; padding: 2px 0;">Needs Audit</td>
                <td style="width: 36%; font-weight: bold; color: #475569; padding: 2px 0; text-align: right;">Coverage Status</td>
            </tr>
            <tr>
                <td style="font-size: 11px; font-weight: bold; color: #0f172a; padding: 1px 0;">{{ $summary['total'] }}</td>
                <td style="font-size: 11px; font-weight: bold; color: #16a34a; padding: 1px 0;">{{ $summary['audited'] }}</td>
                <td style="font-size: 11px; font-weight: bold; color: #d97706; padding: 1px 0;">{{ $summary['aging'] }}</td>
                <td style="font-size: 11px; font-weight: bold; color: #dc2626; padding: 1px 0;">{{ $summary['needs_audit'] }}</td>
                <td style="font-size: 11px; font-weight: bold; color: #2563eb; padding: 1px 0; text-align: right;">
                    {{ $summary['coverage'] }}% <span style="font-size: 8px; font-weight: normal; color: #64748b;">({{ $summary['audited'] }} / {{ $summary['total'] }})</span>
                </td>
            </tr>
        </table>
    </div>

    <!-- MAIN TABLE -->
    <table class="content-table">
        <thead>
            <tr>
                <th style="width: 3%;" class="text-center">No</th>
                <th style="width: 10%;">Bin Location</th>
                <th style="width: 12%;">Item Code</th>
                <th style="width: 25%;">Item Name</th>
                <th style="width: 8%;" class="text-center">Qty</th>
                <th style="width: 10%;">Last Audit</th>
                <th style="width: 8%;">Audit Age</th>
                <th style="width: 13%;">Next Due / Overdue</th>
                <th style="width: 13%;">Last Auditor</th>
                <th style="width: 8%;" class="text-center">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($items as $index => $item)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td style="font-weight: bold; font-family: monospace;">{{ $item->bin_code }}</td>
                    <td style="font-family: monospace;">{{ $item->item_code }}</td>
                    <td style="font-weight: 500; text-transform: uppercase;">{{ $item->item_name }}</td>
                    <td class="text-center" style="font-weight: bold;">{{ (int)$item->current_stock }}</td>
                    <td>{{ $item->last_audit_date }}</td>
                    <td>{{ $item->age }}</td>
                    <td>
                        @if($item->last_audit_date !== 'NEVER')
                            @if($item->is_overdue)
                                <span class="overdue-text">Overdue {{ $item->overdue_days }} days</span>
                            @else
                                <span>Next Due {{ $item->next_due_date }}</span>
                            @endif
                        @else
                            <span style="color: #94a3b8;">-</span>
                        @endif
                    </td>
                    <td>{{ $item->last_auditor }}</td>
                    <td class="text-center status-badge status-{{ $item->status }}">
                        {{ $item->status_label }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- SIGNATURES SECTION -->
    <div class="signature-container" style="margin-top: 35px; page-break-inside: avoid;">
        <table style="width: 100%; font-size: 8px; border-collapse: collapse;">
            <tr>
                <td style="width: 50%; text-align: left; vertical-align: top;">
                    <div style="font-weight: bold; margin-bottom: 45px;">Prepared By,</div>
                    <div style="margin-bottom: 2px;">_______________________________</div>
                    <div style="font-weight: bold; color: #1e293b;">Warehouse Admin</div>
                    <div style="color: #64748b; font-size: 7.5px; margin-top: 1px;">Sign Date: ____________________</div>
                </td>
                <td style="width: 50%; text-align: right; vertical-align: top;">
                    <div style="font-weight: bold; margin-bottom: 45px; text-align: right;">Reviewed & Approved,</div>
                    <div style="margin-bottom: 2px; text-align: right;">_______________________________</div>
                    <div style="font-weight: bold; text-align: right; color: #1e293b;">PPIC Manager</div>
                    <div style="color: #64748b; font-size: 7.5px; text-align: right; margin-top: 1px;">Sign Date: ____________________</div>
                </td>
            </tr>
        </table>
    </div>
</body>
</html>
